from .i_eviction_policy import ICacheStrategy
from .cache_eviction_policy import SimpleCache
from .lru_eviction_policy import LRUEvictionPolicy
from .ttl_eviction_policy import TTLEvictionPolicy
from .sliding_window_eviction_policy import SlidingWindowEvictionPolicy
